# Generated by Django 3.2.9 on 2021-11-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='complete',
        ),
    ]
