# Generated by Django 3.2.9 on 2021-11-28 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_completed_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
